import type { BranchRecord, WorldRecord, WorldSnapshot } from './types';

export const WORLD_CATALOG: WorldRecord[] = [
  {
    id: 'worldgen-prime',
    name: 'WorldGen Prime',
    kind: 'GENERATED',
    epistemicClass: 'GENERATED',
    surfaceEpistemicClass: 'GENERATED',
    fidelity: 'FIELD',
    provider: 'Procedural WorldGen',
    spatialReference: 'LOCAL_PROCEDURAL',
    description: 'Credential-free procedural world and fallback rendering substrate.',
    planetary: {
      gravityG: 1,
      massEarths: 1,
      radiusKm: 6371,
      rotationPeriodHours: 24,
      orbitalPeriodDays: 365.25,
      atmosphere: 'Generated Earth-like atmosphere',
      surfacePressure: 'Generated Earth-like baseline',
      temperature: 'Temperate synthetic range',
      radiation: 'Synthetic baseline',
      illumination: 'Single-star day/night cycle',
      terrainSourceStatus: 'Procedurally generated terrain',
      surfaceRenderingClass: 'GENERATED',
      lightTime: 'Local simulation',
      referenceFrame: 'Local procedural frame',
      habitability: {
        microbial: 'Generated scenario',
        complexLife: 'Generated scenario',
        unprotectedHuman: 'Generated scenario',
        supportedSettlement: 'Generated scenario',
      },
    },
  },
  {
    id: 'new-bedford-001',
    name: 'New Bedford · World #001',
    kind: 'EARTH',
    epistemicClass: 'RECONSTRUCTED',
    surfaceEpistemicClass: 'RECONSTRUCTED',
    fidelity: 'COHORT',
    provider: 'Open Earth + versioned public-data package · procedural fallback available',
    spatialReference: 'EPSG:4326',
    description: 'Real-city proving ground backed by public source metadata, OpenStreetMap/OpenFreeMap geography, and an explicit provenance package. It remains a reconstruction, not a complete photogrammetric digital twin.',
    planetary: {
      gravityG: 1,
      massEarths: 1,
      radiusKm: 6371,
      rotationPeriodHours: 23.934,
      orbitalPeriodDays: 365.256,
      atmosphere: 'Earth',
      surfacePressure: 'Earth surface baseline; local weather is not modeled as a canonical feed',
      temperature: 'Local observational adapter is not yet canonical',
      radiation: 'Earth surface baseline',
      illumination: 'Solar',
      terrainSourceStatus: 'MassGIS/USGS terrain sources referenced; current free map view does not claim those rasters are rendered',
      surfaceRenderingClass: 'RECONSTRUCTED',
      lightTime: 'Local',
      referenceFrame: 'WGS84 / Earth-fixed visualization frame',
      physicalStateSources: ['massgis-parcels-2026', 'massgis-buildings-2026', 'massgis-aerial-2025'],
      habitability: {
        microbial: 'Observed terrestrial environment',
        complexLife: 'Observed terrestrial environment',
        unprotectedHuman: 'Generally viable; local conditions vary',
        supportedSettlement: 'Established urban settlement',
      },
    },
  },
  {
    id: 'moon',
    name: 'Moon',
    kind: 'SOLAR_SYSTEM',
    epistemicClass: 'OBSERVED',
    surfaceEpistemicClass: 'GENERATED',
    fidelity: 'FIELD',
    provider: 'NASA reference metadata · procedural visual surface',
    spatialReference: 'MOON_BODY_FIXED_CONCEPT',
    description: 'Observed lunar identity with generated local rendering. NASA reference data informs descriptive physical state; the browser surface is not an observed terrain reconstruction.',
    planetary: {
      gravityG: 0.166,
      massEarths: 0.0123,
      radiusKm: 1740,
      rotationPeriodHours: 648,
      orbitalPeriodDays: 27,
      atmosphere: 'Very thin, tenuous exosphere; not breathable',
      surfacePressure: 'Effectively vacuum for human exposure',
      temperature: 'Approximately 127°C in full Sun to -173°C in darkness',
      radiation: 'No substantial atmosphere or global magnetic protection comparable to Earth',
      illumination: 'Solar; long lunar day/night cycle',
      terrainSourceStatus: 'Observed lunar mapping exists; not wired into the v0.7 browser surface',
      surfaceRenderingClass: 'GENERATED',
      lightTime: 'About 1.3 seconds one-way at average Earth-Moon distance',
      referenceFrame: 'Moon body-fixed conceptual frame',
      physicalStateSources: ['NASA Science: Moon Facts'],
      habitability: {
        microbial: 'No evidence of indigenous life; extreme surface environment',
        complexLife: 'Not naturally viable',
        unprotectedHuman: 'Not viable',
        supportedSettlement: 'Requires pressure, thermal control, radiation protection, and life support',
      },
    },
  },
  {
    id: 'mars',
    name: 'Mars',
    kind: 'SOLAR_SYSTEM',
    epistemicClass: 'OBSERVED',
    surfaceEpistemicClass: 'GENERATED',
    fidelity: 'FIELD',
    provider: 'NASA reference metadata · procedural visual surface',
    spatialReference: 'MARS_BODY_FIXED_CONCEPT',
    description: 'Observed planetary identity with explicitly generated local visualization. The rendered surface is not claimed as an observed reconstruction.',
    planetary: {
      gravityG: 0.38,
      massEarths: 0.107,
      radiusKm: 3390,
      rotationPeriodHours: 24.6,
      orbitalPeriodDays: 687,
      atmosphere: 'Thin atmosphere dominated by carbon dioxide, with nitrogen and argon',
      surfacePressure: 'Very low relative to Earth sea level',
      temperature: 'Roughly 20°C high to -153°C low in NASA reference ranges',
      radiation: 'Elevated relative to Earth surface',
      illumination: 'Solar · reduced intensity relative to Earth',
      terrainSourceStatus: 'Observed Mars terrain datasets exist; not wired into the v0.7 browser surface',
      surfaceRenderingClass: 'GENERATED',
      lightTime: 'Minutes from Earth; varies with orbital geometry',
      referenceFrame: 'Mars body-fixed conceptual frame',
      physicalStateSources: ['NASA Science: Mars Facts'],
      habitability: {
        microbial: 'Past habitability is an active research target; current surface life is not established',
        complexLife: 'Not established',
        unprotectedHuman: 'Not viable',
        supportedSettlement: 'Requires substantial pressure, radiation, thermal, water, and life-support systems',
      },
    },
  },
  {
    id: 'venus',
    name: 'Venus',
    kind: 'SOLAR_SYSTEM',
    epistemicClass: 'OBSERVED',
    surfaceEpistemicClass: 'GENERATED',
    fidelity: 'FIELD',
    provider: 'NASA reference metadata · procedural visual surface',
    spatialReference: 'VENUS_BODY_FIXED_CONCEPT',
    description: 'Observed Venus identity with generated local rendering. The current browser scene does not reproduce measured Venus topography.',
    planetary: {
      gravityG: 0.904,
      massEarths: 0.815,
      radiusKm: 6052,
      rotationPeriodHours: 5832,
      orbitalPeriodDays: 225,
      atmosphere: 'Dense carbon-dioxide atmosphere with sulfuric-acid clouds',
      surfacePressure: 'About 93 times Earth sea-level pressure',
      temperature: 'About 467°C at the surface in NASA reference material',
      radiation: 'Dense atmosphere changes surface radiation environment; not modeled numerically here',
      illumination: 'Solar · inner Solar System',
      terrainSourceStatus: 'Observed Venus radar/topography data exists; not wired into the v0.7 browser surface',
      surfaceRenderingClass: 'GENERATED',
      lightTime: 'Interplanetary; varies with Earth-Venus geometry',
      referenceFrame: 'Venus body-fixed conceptual frame',
      physicalStateSources: ['NASA Science: Venus Facts'],
      habitability: {
        microbial: 'No compelling evidence of life; cloud-layer habitability remains a research question',
        complexLife: 'Not established',
        unprotectedHuman: 'Not viable',
        supportedSettlement: 'Surface settlement would require extreme pressure and thermal protection',
      },
    },
  },
  {
    id: 'europa',
    name: 'Europa',
    kind: 'SOLAR_SYSTEM',
    epistemicClass: 'OBSERVED',
    surfaceEpistemicClass: 'GENERATED',
    fidelity: 'FIELD',
    provider: 'NASA reference metadata · procedural visual surface',
    spatialReference: 'EUROPA_BODY_FIXED_CONCEPT',
    description: 'Observed Jovian moon identity with generated local rendering and candidate subsurface-world scenarios separated from observation.',
    planetary: {
      gravityG: 0.134,
      massEarths: 0.008,
      radiusKm: 1560.8,
      rotationPeriodHours: 85.23,
      orbitalPeriodDays: 3.551,
      atmosphere: 'Extremely tenuous oxygen atmosphere',
      surfacePressure: 'Extremely low / effectively vacuum for human exposure',
      temperature: 'Cryogenic surface',
      radiation: 'Very high surface radiation',
      illumination: 'Solar · Jupiter system',
      terrainSourceStatus: 'Observed Europa imaging exists; not wired into the v0.7 browser surface',
      surfaceRenderingClass: 'GENERATED',
      lightTime: 'Tens of minutes from Earth; varies by orbit',
      referenceFrame: 'Europa body-fixed conceptual frame',
      physicalStateSources: ['NASA planetary-science reference metadata'],
      habitability: {
        microbial: 'Candidate subsurface habitability; unconfirmed',
        complexLife: 'Unknown',
        unprotectedHuman: 'Not viable',
        supportedSettlement: 'Highly demanding',
      },
    },
  },
  {
    id: 'titan',
    name: 'Titan',
    kind: 'SOLAR_SYSTEM',
    epistemicClass: 'OBSERVED',
    surfaceEpistemicClass: 'GENERATED',
    fidelity: 'FIELD',
    provider: 'NASA/Cassini-Huygens reference metadata · procedural visual surface',
    spatialReference: 'TITAN_BODY_FIXED_CONCEPT',
    description: 'Observed Titan identity with generated browser surface. Its dense atmosphere, hydrocarbon surface liquids, and candidate subsurface ocean are represented descriptively rather than as a calibrated physical twin.',
    planetary: {
      gravityG: 0.14,
      massEarths: 0.0225,
      radiusKm: 2575,
      rotationPeriodHours: 382,
      orbitalPeriodDays: 15.92,
      atmosphere: 'Dense atmosphere, about 95% nitrogen and about 5% methane with trace compounds',
      surfacePressure: 'About 60% greater than Earth surface pressure',
      temperature: 'About -179°C at the surface',
      radiation: 'Saturn-system particle environment; not numerically modeled here',
      illumination: 'Solar · roughly 100 times fainter than Earth at Saturn/Titan distance',
      terrainSourceStatus: 'Cassini-Huygens observations exist; not wired into the v0.7 browser surface',
      surfaceRenderingClass: 'GENERATED',
      lightTime: 'Interplanetary; varies with Earth-Saturn geometry',
      referenceFrame: 'Titan body-fixed conceptual frame',
      physicalStateSources: ['NASA Science: Titan Facts', 'Cassini-Huygens'],
      habitability: {
        microbial: 'Potentially interesting subsurface and hydrocarbon environments; no evidence of life',
        complexLife: 'Not established',
        unprotectedHuman: 'Not viable',
        supportedSettlement: 'Requires thermal, oxygen, radiation/environmental, and life-support systems',
      },
    },
  },
  {
    id: 'exoworld-a',
    name: 'Asterion · Thin Atmosphere',
    kind: 'EXOWORLD',
    familyId: 'asterion-family',
    variantId: 'thin',
    epistemicClass: 'SPECULATIVE',
    surfaceEpistemicClass: 'SPECULATIVE',
    fidelity: 'FIELD',
    provider: 'Procedural exoworld family',
    spatialReference: 'SYNTHETIC_EXOWORLD',
    description: 'Synthetic thin-atmosphere variant in the Asterion candidate family. No claim is made that Asterion is an observed exoplanet.',
    planetary: {
      gravityG: 0.92,
      massEarths: 0.82,
      radiusKm: 6100,
      rotationPeriodHours: 31,
      orbitalPeriodDays: 241,
      atmosphere: 'Synthetic thin-atmosphere scenario',
      surfacePressure: 'Synthetic low-pressure scenario',
      temperature: 'Synthetic model-family state',
      radiation: 'Synthetic model-family state',
      illumination: 'Synthetic K-type host-star scenario',
      terrainSourceStatus: 'Procedural / no observed terrain',
      surfaceRenderingClass: 'SPECULATIVE',
      lightTime: 'Synthetic interstellar observation context',
      referenceFrame: 'Synthetic body-fixed candidate frame',
      habitability: { microbial: 'Scenario dependent', complexLife: 'Scenario dependent', unprotectedHuman: 'Unknown', supportedSettlement: 'Unknown' },
    },
  },
  {
    id: 'exoworld-asterion-temperate',
    name: 'Asterion · Temperate Atmosphere',
    kind: 'EXOWORLD',
    familyId: 'asterion-family',
    variantId: 'temperate',
    epistemicClass: 'SPECULATIVE',
    surfaceEpistemicClass: 'SPECULATIVE',
    fidelity: 'FIELD',
    provider: 'Procedural exoworld family',
    spatialReference: 'SYNTHETIC_EXOWORLD',
    description: 'Synthetic temperate-atmosphere variant used to demonstrate constrained world families rather than one falsely authoritative exoplanet surface.',
    planetary: {
      gravityG: 0.92, massEarths: 0.82, radiusKm: 6100, rotationPeriodHours: 31, orbitalPeriodDays: 241,
      atmosphere: 'Synthetic temperate mixed-atmosphere scenario', surfacePressure: 'Synthetic moderate-pressure scenario',
      temperature: 'Synthetic temperate model-family state', radiation: 'Synthetic model-family state', illumination: 'Synthetic K-type host-star scenario',
      terrainSourceStatus: 'Procedural / no observed terrain', surfaceRenderingClass: 'SPECULATIVE', lightTime: 'Synthetic interstellar observation context', referenceFrame: 'Synthetic body-fixed candidate frame',
      habitability: { microbial: 'Scenario dependent', complexLife: 'Scenario dependent', unprotectedHuman: 'Unknown', supportedSettlement: 'Unknown' },
    },
  },
  {
    id: 'exoworld-asterion-dense',
    name: 'Asterion · Dense Atmosphere',
    kind: 'EXOWORLD',
    familyId: 'asterion-family',
    variantId: 'dense',
    epistemicClass: 'SPECULATIVE',
    surfaceEpistemicClass: 'SPECULATIVE',
    fidelity: 'FIELD',
    provider: 'Procedural exoworld family',
    spatialReference: 'SYNTHETIC_EXOWORLD',
    description: 'Synthetic dense-atmosphere variant in the same Asterion possibility family.',
    planetary: {
      gravityG: 0.92, massEarths: 0.82, radiusKm: 6100, rotationPeriodHours: 31, orbitalPeriodDays: 241,
      atmosphere: 'Synthetic dense-atmosphere scenario', surfacePressure: 'Synthetic high-pressure scenario',
      temperature: 'Synthetic greenhouse model-family state', radiation: 'Synthetic model-family state', illumination: 'Synthetic K-type host-star scenario',
      terrainSourceStatus: 'Procedural / no observed terrain', surfaceRenderingClass: 'SPECULATIVE', lightTime: 'Synthetic interstellar observation context', referenceFrame: 'Synthetic body-fixed candidate frame',
      habitability: { microbial: 'Scenario dependent', complexLife: 'Scenario dependent', unprotectedHuman: 'Unknown', supportedSettlement: 'Unknown' },
    },
  },
];

function snapshot(id: string, branchId: string, year: number, metrics: Record<string, number>, eventIds: string[] = []): WorldSnapshot {
  const metricText = Object.entries(metrics).sort(([a], [b]) => a.localeCompare(b)).map(([key, value]) => `${key}:${value}`).join('|');
  return {
    id,
    worldId: 'worldgen-prime',
    branchId,
    year,
    metrics,
    eventIds,
    commitment: `${branchId}:${year}:${metricText}`,
  };
}

export const ROOT_BRANCH: BranchRecord = {
  id: 'branch-root',
  label: 'Baseline',
  parentId: null,
  forkYear: 2026,
  seed: 424242,
  events: [
    { id: 'event-2030', year: 2030, type: 'transition', label: 'Urban systems adjustment', delta: { vitality: 2, resilience: 1 } },
    { id: 'event-2035', year: 2035, type: 'transition', label: 'Infrastructure renewal', delta: { vitality: 3, resilience: 4 } },
  ],
  snapshots: [
    snapshot('snap-2026-root', 'branch-root', 2026, { vitality: 72, resilience: 64, affordability: 58, population: 184000 }),
    snapshot('snap-2030-root', 'branch-root', 2030, { vitality: 74, resilience: 65, affordability: 57, population: 185200 }, ['event-2030']),
    snapshot('snap-2035-root', 'branch-root', 2035, { vitality: 77, resilience: 69, affordability: 56, population: 187400 }, ['event-2035']),
    snapshot('snap-2040-root', 'branch-root', 2040, { vitality: 79, resilience: 71, affordability: 55, population: 189100 }),
  ],
};
