import type { BranchRecord, WorldRecord, WorldSnapshot } from './types';

export const WORLD_CATALOG: WorldRecord[] = [
  {
    id: 'worldgen-prime',
    name: 'WorldGen Prime',
    kind: 'GENERATED',
    epistemicClass: 'GENERATED',
    surfaceEpistemicClass: 'GENERATED',
    fidelity: 'FIELD',
    provider: 'Procedural WorldGen',
    spatialReference: 'LOCAL_PROCEDURAL',
    description: 'Credential-free procedural world and fallback rendering substrate.',
    planetary: {
      gravityG: 1,
      radiusKm: 6371,
      rotationPeriodHours: 24,
      orbitalPeriodDays: 365.25,
      atmosphere: 'Generated Earth-like atmosphere',
      surfacePressure: 'Generated Earth-like baseline',
      temperature: 'Temperate synthetic range',
      radiation: 'Synthetic baseline',
      illumination: 'Single-star day/night cycle',
      lightTime: 'Local simulation',
      referenceFrame: 'Local procedural frame',
      habitability: {
        microbial: 'Generated scenario',
        complexLife: 'Generated scenario',
        unprotectedHuman: 'Generated scenario',
        supportedSettlement: 'Generated scenario',
      },
    },
  },
  {
    id: 'new-bedford-001',
    name: 'New Bedford · World #001',
    kind: 'EARTH',
    epistemicClass: 'RECONSTRUCTED',
    surfaceEpistemicClass: 'RECONSTRUCTED',
    fidelity: 'COHORT',
    provider: 'Open Earth + versioned public-data package · procedural fallback available',
    spatialReference: 'EPSG:4326',
    description: 'Real-city proving ground backed by public source metadata, OpenStreetMap/OpenFreeMap geography, and an explicit provenance package. It remains a reconstruction, not a complete photogrammetric digital twin.',
    planetary: {
      gravityG: 1,
      radiusKm: 6371,
      rotationPeriodHours: 23.934,
      orbitalPeriodDays: 365.256,
      atmosphere: 'Earth',
      surfacePressure: 'Earth surface baseline; local weather not modeled in v0.2',
      temperature: 'Local observational adapter not yet canonical',
      radiation: 'Earth surface baseline',
      illumination: 'Solar',
      lightTime: 'Local',
      referenceFrame: 'WGS84 / Earth-fixed visualization frame',
      physicalStateSources: ['massgis-parcels-2026', 'massgis-buildings-2026', 'massgis-aerial-2025'],
      habitability: {
        microbial: 'Observed terrestrial environment',
        complexLife: 'Observed terrestrial environment',
        unprotectedHuman: 'Generally viable; local conditions vary',
        supportedSettlement: 'Established urban settlement',
      },
    },
  },
  {
    id: 'mars',
    name: 'Mars',
    kind: 'SOLAR_SYSTEM',
    epistemicClass: 'OBSERVED',
    surfaceEpistemicClass: 'GENERATED',
    fidelity: 'FIELD',
    provider: 'Worldline planetary metadata · procedural visual fallback',
    spatialReference: 'MARS_BODY_FIXED_CONCEPT',
    description: 'Observed planetary identity with explicitly generated local visualization. The rendered surface is not claimed as an observed reconstruction.',
    planetary: {
      gravityG: 0.38,
      radiusKm: 3389.5,
      rotationPeriodHours: 24.623,
      orbitalPeriodDays: 686.98,
      atmosphere: 'Thin CO₂-dominated atmosphere',
      surfacePressure: 'About 0.6% of Earth sea-level pressure; descriptive model value',
      temperature: 'Cold, highly variable',
      radiation: 'Elevated relative to Earth surface',
      illumination: 'Solar · reduced intensity',
      lightTime: 'Minutes from Earth; varies by orbit',
      referenceFrame: 'Mars body-fixed conceptual frame',
      physicalStateSources: ['NASA/planetary-science reference metadata adapter pending'],
      habitability: {
        microbial: 'Unknown / research question',
        complexLife: 'Not established',
        unprotectedHuman: 'Not viable',
        supportedSettlement: 'Requires substantial life support',
      },
    },
  },
  {
    id: 'europa',
    name: 'Europa',
    kind: 'SOLAR_SYSTEM',
    epistemicClass: 'OBSERVED',
    surfaceEpistemicClass: 'GENERATED',
    fidelity: 'FIELD',
    provider: 'Worldline planetary metadata · procedural visual fallback',
    spatialReference: 'EUROPA_BODY_FIXED_CONCEPT',
    description: 'Observed Jovian moon identity with generated local rendering and candidate subsurface-world scenarios separated from observation.',
    planetary: {
      gravityG: 0.134,
      radiusKm: 1560.8,
      rotationPeriodHours: 85.23,
      orbitalPeriodDays: 3.551,
      atmosphere: 'Extremely tenuous oxygen atmosphere',
      surfacePressure: 'Extremely low / effectively vacuum for human exposure',
      temperature: 'Cryogenic surface',
      radiation: 'Very high surface radiation',
      illumination: 'Solar · Jupiter system',
      lightTime: 'Tens of minutes from Earth; varies by orbit',
      referenceFrame: 'Europa body-fixed conceptual frame',
      physicalStateSources: ['NASA/planetary-science reference metadata adapter pending'],
      habitability: {
        microbial: 'Candidate subsurface habitability; unconfirmed',
        complexLife: 'Unknown',
        unprotectedHuman: 'Not viable',
        supportedSettlement: 'Highly demanding',
      },
    },
  },
  {
    id: 'exoworld-a',
    name: 'Asterion Candidate Family',
    kind: 'EXOWORLD',
    epistemicClass: 'SPECULATIVE',
    surfaceEpistemicClass: 'SPECULATIVE',
    fidelity: 'FIELD',
    provider: 'Procedural exoworld family',
    spatialReference: 'SYNTHETIC_EXOWORLD',
    description: 'Synthetic constrained-world family used to demonstrate uncertainty-aware extraterrestrial exploration.',
    planetary: {
      gravityG: 0.92,
      radiusKm: 6100,
      rotationPeriodHours: 31,
      orbitalPeriodDays: 241,
      atmosphere: 'Candidate families: thin / temperate / dense',
      surfacePressure: 'Model-family dependent',
      temperature: 'Model-family dependent',
      radiation: 'Model-family dependent',
      illumination: 'K-type host-star scenario',
      lightTime: 'Interstellar observation only',
      referenceFrame: 'Synthetic body-fixed candidate frame',
      habitability: {
        microbial: 'Scenario dependent',
        complexLife: 'Scenario dependent',
        unprotectedHuman: 'Unknown',
        supportedSettlement: 'Unknown',
      },
    },
  },
];

function snapshot(id: string, branchId: string, year: number, metrics: Record<string, number>, eventIds: string[] = []): WorldSnapshot {
  const metricText = Object.entries(metrics).sort(([a], [b]) => a.localeCompare(b)).map(([key, value]) => `${key}:${value}`).join('|');
  return {
    id,
    worldId: 'worldgen-prime',
    branchId,
    year,
    metrics,
    eventIds,
    commitment: `${branchId}:${year}:${metricText}`,
  };
}

export const ROOT_BRANCH: BranchRecord = {
  id: 'branch-root',
  label: 'Baseline',
  parentId: null,
  forkYear: 2026,
  seed: 424242,
  events: [
    { id: 'event-2030', year: 2030, type: 'transition', label: 'Urban systems adjustment', delta: { vitality: 2, resilience: 1 } },
    { id: 'event-2035', year: 2035, type: 'transition', label: 'Infrastructure renewal', delta: { vitality: 3, resilience: 4 } },
  ],
  snapshots: [
    snapshot('snap-2026-root', 'branch-root', 2026, { vitality: 72, resilience: 64, affordability: 58, population: 184000 }),
    snapshot('snap-2030-root', 'branch-root', 2030, { vitality: 74, resilience: 65, affordability: 57, population: 185200 }, ['event-2030']),
    snapshot('snap-2035-root', 'branch-root', 2035, { vitality: 77, resilience: 69, affordability: 56, population: 187400 }, ['event-2035']),
    snapshot('snap-2040-root', 'branch-root', 2040, { vitality: 79, resilience: 71, affordability: 55, population: 189100 }),
  ],
};
